name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.25.3

    - name: Install dependencies
      run: go mod download
      env:
        GOPATH: /home/runner/work/instllr/go

    - name: Run Tests
      run: go test
      env:
        GOPATH: /home/runner/work/instllr/go

    - name: Build
      run: make
      env:
        GOPATH: /home/runner/work/instllr/go
